all :
	clear
	g++ -std=c++11 -Wall -o A A.cpp
	g++ -std=c++11 -Wall -o B B.cpp
	g++ -std=c++11 -Wall -o C C.cpp
	g++ -std=c++11 -Wall -o D D.cpp
	g++ -std=c++11 -Wall -o E E.cpp
	g++ -std=c++11 -Wall -o F F.cpp
% :
	g++ -std=c++11 -Wall -o $@ $@.cpp
