#include <stdio.h>
#include <string>
#include <vector>

using namespace std;

int main() {

	vector <string> name, prop;

	name.push_back("");
	prop.push_back("");

	// 1
	name.push_back("Bulbasaur");
	prop.push_back("Grass Poison");
	name.push_back("Ivysaur");
	prop.push_back("Grass Poison");
	name.push_back("Venusaur");
	prop.push_back("Grass Poison");
	name.push_back("Charmander");
	prop.push_back("Fire");
	name.push_back("Charmeleon");
	prop.push_back("Fire");
	name.push_back("Charizard");
	prop.push_back("Fire Flying");
	name.push_back("Squirtle");
	prop.push_back("Water");
	name.push_back("Wartortle");
	prop.push_back("Water");
	name.push_back("Blastoise");
	prop.push_back("Water");
	name.push_back("Caterpie");
	prop.push_back("Bug");
	name.push_back("Metapod");
	prop.push_back("Bug");
	name.push_back("Butterfree");
	prop.push_back("Bug Flying");
	name.push_back("Weedle");
	prop.push_back("Bug Poison");
	name.push_back("Kakuna");
	prop.push_back("Bug Poison");
	name.push_back("Beedrill");
	prop.push_back("Bug Poison");
	name.push_back("Pidgey");
	prop.push_back("Normal Flying");
	name.push_back("Pidgeotto");
	prop.push_back("Normal Flying");
	name.push_back("Pidgeot");
	prop.push_back("Normal Flying");
	name.push_back("Rattata");
	prop.push_back("Normal");
	name.push_back("Raticate");
	prop.push_back("Normal");

	// 21
	name.push_back("Spearow");
	prop.push_back("Normal Flying");
	name.push_back("Fearow");
	prop.push_back("Normal Flying");
	name.push_back("Ekans");
	prop.push_back("Poison");
	name.push_back("Arbok");
	prop.push_back("Poison");
	name.push_back("Pikachu");
	prop.push_back("Electric");
	name.push_back("Raichu");
	prop.push_back("Electric");
	name.push_back("Sandshrew");
	prop.push_back("Ground");
	name.push_back("Sandslash");
	prop.push_back("Ground");
	// 29
	name.push_back("Nidoran♀");
	prop.push_back("Poison");
	name.push_back("Nidorina");
	prop.push_back("Poison");
	name.push_back("Nidoqueen");
	prop.push_back("Poison Ground");
	// 32
	name.push_back("Nidoran♂");
	prop.push_back("Poison");
	name.push_back("Nidorino");
	prop.push_back("Poison");
	name.push_back("Nidoking");
	prop.push_back("Poison Ground");
	name.push_back("Clefairy");
	prop.push_back("Fairy");
	name.push_back("Clefable");
	prop.push_back("Fairy");
	name.push_back("Vulpix");
	prop.push_back("Fire");
	name.push_back("Ninetales");
	prop.push_back("Fire");
	name.push_back("Jigglypuff");
	prop.push_back("Normal Fairy");
	name.push_back("Wigglytuff");
	prop.push_back("Normal Fairy");
	name.push_back("Zubat");
	prop.push_back("Poison Flying");
	name.push_back("Golbat");
	prop.push_back("Poison Flying");
	name.push_back("Oddish");
	prop.push_back("Grass Poison");
	name.push_back("Gloom");
	prop.push_back("Grass Poison");
	name.push_back("Vileplume");
	prop.push_back("Grass Poison");
	name.push_back("Paras");
	prop.push_back("Bug Grass");
	name.push_back("Parasect");
	prop.push_back("Bug Grass");
	name.push_back("Venonat");
	prop.push_back("Bug Poison");
	name.push_back("Venomoth");
	prop.push_back("Bug Poison");
	name.push_back("Diglett");
	prop.push_back("Ground");
	name.push_back("Dugtrio");
	prop.push_back("Ground");
	name.push_back("Meowth");
	prop.push_back("Normal");
	name.push_back("Persian");
	prop.push_back("Normal");
	name.push_back("Psyduck");
	prop.push_back("Water");
	name.push_back("Golduck");
	prop.push_back("Water");
	name.push_back("Mankey");
	prop.push_back("Fighting");
	name.push_back("Primeape");
	prop.push_back("Fighting");
	name.push_back("Growlithe");
	prop.push_back("Fire");
	name.push_back("Arcanine");
	prop.push_back("Fire");
	name.push_back("Poliwag");
	prop.push_back("Water");
	name.push_back("Poliwhirl");
	prop.push_back("Water");
	name.push_back("Poliwrath");
	prop.push_back("Water Fighting");
	name.push_back("Abra");
	prop.push_back("Psychic");
	name.push_back("Kadabra");
	prop.push_back("Psychic");
	name.push_back("Alakazam");
	prop.push_back("Psychic");
	name.push_back("Machop");
	prop.push_back("Fighting");
	name.push_back("Machoke");
	prop.push_back("Fighting");
	name.push_back("Machamp");
	prop.push_back("Fighting");
	name.push_back("Bellsprout");
	prop.push_back("Grass Poison");
	name.push_back("Weepinbell");
	prop.push_back("Grass Poison");
	name.push_back("Victreebel");
	prop.push_back("Grass Poison");
	name.push_back("Tentacool");
	prop.push_back("Water Poison");
	name.push_back("Tentacruel");
	prop.push_back("Water Poison");
	name.push_back("Geodude");
	prop.push_back("Rock Ground");
	name.push_back("Graveler");
	prop.push_back("Rock Ground");
	name.push_back("Golem");
	prop.push_back("Rock Ground");
	name.push_back("Ponyta");
	prop.push_back("Fire");
	name.push_back("Rapidash");
	prop.push_back("Fire");
	name.push_back("Slowpoke");
	prop.push_back("Water Psychic");
	name.push_back("Slowbro");
	prop.push_back("Water Psychic");
	name.push_back("Magnemite");
	prop.push_back("Electric Steel");
	name.push_back("Magneton");
	prop.push_back("Electric Steel");
	name.push_back("Farfetch'd");
	prop.push_back("Normal Flying");
	name.push_back("Doduo");
	prop.push_back("Normal Flying");
	name.push_back("Dodrio");
	prop.push_back("Normal Flying");
	name.push_back("Seel");
	prop.push_back("Water");
	name.push_back("Dewgong");
	prop.push_back("Water Ice");
	name.push_back("Grimer");
	prop.push_back("Poison");
	name.push_back("Muk");
	prop.push_back("Poison");
	name.push_back("Shellder");
	prop.push_back("Water");
	name.push_back("Cloyster");
	prop.push_back("Water Ice");
	name.push_back("Gastly");
	prop.push_back("Ghost Poison");
	name.push_back("Haunter");
	prop.push_back("Ghost Poison");
	name.push_back("Gengar");
	prop.push_back("Ghost Poison");
	name.push_back("Onix");
	prop.push_back("Rock Ground");
	name.push_back("Drowzee");
	prop.push_back("Psychic");
	name.push_back("Hypno");
	prop.push_back("Psychic");
	name.push_back("Krabby");
	prop.push_back("Water");
	name.push_back("Kingler");
	prop.push_back("Water");
	name.push_back("Voltorb");
	prop.push_back("Electric");
	name.push_back("Electrode");
	prop.push_back("Electric");
	name.push_back("Exeggcute");
	prop.push_back("Grass Psychic");
	name.push_back("Exeggutor");
	prop.push_back("Grass Psychic");
	name.push_back("Cubone");
	prop.push_back("Ground");
	name.push_back("Marowak");
	prop.push_back("Ground");
	name.push_back("Hitmonlee");
	prop.push_back("Fighting");
	name.push_back("Hitmonchan");
	prop.push_back("Fighting");
	name.push_back("Lickitung");
	prop.push_back("Normal");
	name.push_back("Koffing");
	prop.push_back("Poison");
	name.push_back("Weezing");
	prop.push_back("Poison");
	name.push_back("Rhyhorn");
	prop.push_back("Ground Rock");
	name.push_back("Rhydon");
	prop.push_back("Ground Rock");
	name.push_back("Chansey");
	prop.push_back("Normal");
	name.push_back("Tangela");
	prop.push_back("Grass");
	name.push_back("Kangaskhan");
	prop.push_back("Normal");
	name.push_back("Horsea");
	prop.push_back("Water");
	name.push_back("Seadra");
	prop.push_back("Water");
	name.push_back("Goldeen");
	prop.push_back("Water");
	name.push_back("Seaking");
	prop.push_back("Water");
	name.push_back("Staryu");
	prop.push_back("Water");
	name.push_back("Starmie");
	prop.push_back("Water Psychic");

	// 122
	name.push_back("Mr. Mime");
	prop.push_back("Psychic Fairy");
	name.push_back("Scyther");
	prop.push_back("Bug Flying");
	name.push_back("Jynx");
	prop.push_back("Ice Psychic");
	name.push_back("Electabuzz");
	prop.push_back("Electric");
	name.push_back("Magmar");
	prop.push_back("Fire");
	name.push_back("Pinsir");
	prop.push_back("Bug");
	name.push_back("Tauros");
	prop.push_back("Normal");
	name.push_back("Magikarp");
	prop.push_back("Water");
	name.push_back("Gyarados");
	prop.push_back("Water Flying");
	name.push_back("Lapras");
	prop.push_back("Water Ice");
	name.push_back("Ditto");
	prop.push_back("Normal");
	name.push_back("Eevee");
	prop.push_back("Normal");
	name.push_back("Vaporeon");
	prop.push_back("Water");
	name.push_back("Jolteon");
	prop.push_back("Electric");
	name.push_back("Flareon");
	prop.push_back("Fire");
	name.push_back("Porygon");
	prop.push_back("Normal");
	name.push_back("Omanyte");
	prop.push_back("Rock Water");
	name.push_back("Omastar");
	prop.push_back("Rock Water");
	name.push_back("Kabuto");
	prop.push_back("Rock Water");
	name.push_back("Kabutops");
	prop.push_back("Rock Water");
	name.push_back("Aerodactyl");
	prop.push_back("Rock Flying");
	name.push_back("Snorlax");
	prop.push_back("Normal");
	name.push_back("Articuno");
	prop.push_back("Ice Flying");
	name.push_back("Zapdos");
	prop.push_back("Electric Flying");
	name.push_back("Moltres");
	prop.push_back("Fire Flying");
	name.push_back("Dratini");
	prop.push_back("Dragon");
	name.push_back("Dragonair");
	prop.push_back("Dragon");
	name.push_back("Dragonite");
	prop.push_back("Dragon Flying");
	name.push_back("Mewtwo");
	prop.push_back("Psychic");
	name.push_back("Mew");
	prop.push_back("Psychic");
	name.push_back("Chikorita");
	prop.push_back("Grass");
	name.push_back("Bayleef");
	prop.push_back("Grass");
	name.push_back("Meganium");
	prop.push_back("Grass");
	name.push_back("Cyndaquil");
	prop.push_back("Fire");
	name.push_back("Quilava");
	prop.push_back("Fire");
	name.push_back("Typhlosion");
	prop.push_back("Fire");
	name.push_back("Totodile");
	prop.push_back("Water");
	name.push_back("Croconaw");
	prop.push_back("Water");
	name.push_back("Feraligatr");
	prop.push_back("Water");
	name.push_back("Sentret");
	prop.push_back("Normal");
	name.push_back("Furret");
	prop.push_back("Normal");
	name.push_back("Hoothoot");
	prop.push_back("Normal Flying");
	name.push_back("Noctowl");
	prop.push_back("Normal Flying");
	name.push_back("Ledyba");
	prop.push_back("Bug Flying");
	name.push_back("Ledian");
	prop.push_back("Bug Flying");
	name.push_back("Spinarak");
	prop.push_back("Bug Poison");
	name.push_back("Ariados");
	prop.push_back("Bug Poison");
	name.push_back("Crobat");
	prop.push_back("Poison Flying");
	name.push_back("Chinchou");
	prop.push_back("Water Electric");
	name.push_back("Lanturn");
	prop.push_back("Water Electric");
	name.push_back("Pichu");
	prop.push_back("Electric");
	name.push_back("Cleffa");
	prop.push_back("Fairy");
	name.push_back("Igglybuff");
	prop.push_back("Normal Fairy");
	name.push_back("Togepi");
	prop.push_back("Fairy");
	name.push_back("Togetic");
	prop.push_back("Fairy Flying");
	name.push_back("Natu");
	prop.push_back("Psychic Flying");
	name.push_back("Xatu");
	prop.push_back("Psychic Flying");
	name.push_back("Mareep");
	prop.push_back("Electric");
	name.push_back("Flaaffy");
	prop.push_back("Electric");
	name.push_back("Ampharos");
	prop.push_back("Electric");
	name.push_back("Bellossom");
	prop.push_back("Grass");
	name.push_back("Marill");
	prop.push_back("Water Fairy");
	name.push_back("Azumarill");
	prop.push_back("Water Fairy");
	name.push_back("Sudowoodo");
	prop.push_back("Rock");
	name.push_back("Politoed");
	prop.push_back("Water");
	name.push_back("Hoppip");
	prop.push_back("Grass Flying");
	name.push_back("Skiploom");
	prop.push_back("Grass Flying");
	name.push_back("Jumpluff");
	prop.push_back("Grass Flying");
	name.push_back("Aipom");
	prop.push_back("Normal");
	name.push_back("Sunkern");
	prop.push_back("Grass");
	name.push_back("Sunflora");
	prop.push_back("Grass");
	name.push_back("Yanma");
	prop.push_back("Bug Flying");
	name.push_back("Wooper");
	prop.push_back("Water Ground");
	name.push_back("Quagsire");
	prop.push_back("Water Ground");
	name.push_back("Espeon");
	prop.push_back("Psychic");
	name.push_back("Umbreon");
	prop.push_back("Dark");
	name.push_back("Murkrow");
	prop.push_back("Dark Flying");
	name.push_back("Slowking");
	prop.push_back("Water Psychic");
	name.push_back("Misdreavus");
	prop.push_back("Ghost");
	name.push_back("Unown");
	prop.push_back("Psychic");
	name.push_back("Wobbuffet");
	prop.push_back("Psychic");
	name.push_back("Girafarig");
	prop.push_back("Normal Psychic");
	name.push_back("Pineco");
	prop.push_back("Bug");
	name.push_back("Forretress");
	prop.push_back("Bug Steel");
	name.push_back("Dunsparce");
	prop.push_back("Normal");
	name.push_back("Gligar");
	prop.push_back("Ground Flying");
	name.push_back("Steelix");
	prop.push_back("Steel Ground");
	name.push_back("Snubbull");
	prop.push_back("Fairy");
	name.push_back("Granbull");
	prop.push_back("Fairy");
	name.push_back("Qwilfish");
	prop.push_back("Water Poison");
	name.push_back("Scizor");
	prop.push_back("Bug Steel");
	name.push_back("Shuckle");
	prop.push_back("Bug Rock");
	name.push_back("Heracross");
	prop.push_back("Bug Fighting");
	name.push_back("Sneasel");
	prop.push_back("Dark Ice");
	name.push_back("Teddiursa");
	prop.push_back("Normal");
	name.push_back("Ursaring");
	prop.push_back("Normal");
	name.push_back("Slugma");
	prop.push_back("Fire");
	name.push_back("Magcargo");
	prop.push_back("Fire Rock");
	name.push_back("Swinub");
	prop.push_back("Ice Ground");
	name.push_back("Piloswine");
	prop.push_back("Ice Ground");
	name.push_back("Corsola");
	prop.push_back("Water Rock");
	name.push_back("Remoraid");
	prop.push_back("Water");
	name.push_back("Octillery");
	prop.push_back("Water");
	name.push_back("Delibird");
	prop.push_back("Ice Flying");
	name.push_back("Mantine");
	prop.push_back("Water Flying");
	name.push_back("Skarmory");
	prop.push_back("Steel Flying");
	name.push_back("Houndour");
	prop.push_back("Dark Fire");
	name.push_back("Houndoom");
	prop.push_back("Dark Fire");
	name.push_back("Kingdra");
	prop.push_back("Water Dragon");
	name.push_back("Phanpy");
	prop.push_back("Ground");
	name.push_back("Donphan");
	prop.push_back("Ground");
	name.push_back("Porygon2");
	prop.push_back("Normal");
	name.push_back("Stantler");
	prop.push_back("Normal");
	name.push_back("Smeargle");
	prop.push_back("Normal");
	name.push_back("Tyrogue");
	prop.push_back("Fighting");
	name.push_back("Hitmontop");
	prop.push_back("Fighting");
	name.push_back("Smoochum");
	prop.push_back("Ice Psychic");
	name.push_back("Elekid");
	prop.push_back("Electric");
	name.push_back("Magby");
	prop.push_back("Fire");
	name.push_back("Miltank");
	prop.push_back("Normal");
	name.push_back("Blissey");
	prop.push_back("Normal");
	name.push_back("Raikou");
	prop.push_back("Electric");
	name.push_back("Entei");
	prop.push_back("Fire");
	name.push_back("Suicune");
	prop.push_back("Water");
	name.push_back("Larvitar");
	prop.push_back("Rock Ground");
	name.push_back("Pupitar");
	prop.push_back("Rock Ground");
	name.push_back("Tyranitar");
	prop.push_back("Rock Dark");
	name.push_back("Lugia");
	prop.push_back("Psychic Flying");

	// 250
	name.push_back("Ho-oh");
	prop.push_back("Fire Flying");
	name.push_back("Celebi");
	prop.push_back("Psychic Grass");
	name.push_back("Treecko");
	prop.push_back("Grass");
	name.push_back("Grovyle");
	prop.push_back("Grass");
	name.push_back("Sceptile");
	prop.push_back("Grass");
	name.push_back("Torchic");
	prop.push_back("Fire");
	name.push_back("Combusken");
	prop.push_back("Fire Fighting");
	name.push_back("Blaziken");
	prop.push_back("Fire Fighting");
	name.push_back("Mudkip");
	prop.push_back("Water");
	name.push_back("Marshtomp");
	prop.push_back("Water Ground");
	name.push_back("Swampert");
	prop.push_back("Water Ground");
	name.push_back("Poochyena");
	prop.push_back("Dark");
	name.push_back("Mightyena");
	prop.push_back("Dark");
	name.push_back("Zigzagoon");
	prop.push_back("Normal");
	name.push_back("Linoone");
	prop.push_back("Normal");
	name.push_back("Wurmple");
	prop.push_back("Bug");
	name.push_back("Silcoon");
	prop.push_back("Bug");
	name.push_back("Beautifly");
	prop.push_back("Bug Flying");
	name.push_back("Cascoon");
	prop.push_back("Bug");
	name.push_back("Dustox");
	prop.push_back("Bug Poison");
	name.push_back("Lotad");
	prop.push_back("Water Grass");
	name.push_back("Lombre");
	prop.push_back("Water Grass");
	name.push_back("Ludicolo");
	prop.push_back("Water Grass");
	name.push_back("Seedot");
	prop.push_back("Grass");
	name.push_back("Nuzleaf");
	prop.push_back("Grass Dark");
	name.push_back("Shiftry");
	prop.push_back("Grass Dark");
	name.push_back("Taillow");
	prop.push_back("Normal Flying");
	name.push_back("Swellow");
	prop.push_back("Normal Flying");
	name.push_back("Wingull");
	prop.push_back("Water Flying");
	name.push_back("Pelipper");
	prop.push_back("Water Flying");
	name.push_back("Ralts");
	prop.push_back("Psychic Fairy");
	name.push_back("Kirlia");
	prop.push_back("Psychic Fairy");
	name.push_back("Gardevoir");
	prop.push_back("Psychic Fairy");
	name.push_back("Surskit");
	prop.push_back("Bug Water");
	name.push_back("Masquerain");
	prop.push_back("Bug Flying");
	name.push_back("Shroomish");
	prop.push_back("Grass");
	name.push_back("Breloom");
	prop.push_back("Grass Fighting");
	name.push_back("Slakoth");
	prop.push_back("Normal");
	name.push_back("Vigoroth");
	prop.push_back("Normal");
	name.push_back("Slaking");
	prop.push_back("Normal");
	name.push_back("Nincada");
	prop.push_back("Bug Ground");
	name.push_back("Ninjask");
	prop.push_back("Bug Flying");
	name.push_back("Shedinja");
	prop.push_back("Bug Ghost");
	name.push_back("Whismur");
	prop.push_back("Normal");
	name.push_back("Loudred");
	prop.push_back("Normal");
	name.push_back("Exploud");
	prop.push_back("Normal");
	name.push_back("Makuhita");
	prop.push_back("Fighting");
	name.push_back("Hariyama");
	prop.push_back("Fighting");
	name.push_back("Azurill");
	prop.push_back("Normal Fairy");
	name.push_back("Nosepass");
	prop.push_back("Rock");
	name.push_back("Skitty");
	prop.push_back("Normal");
	name.push_back("Delcatty");
	prop.push_back("Normal");
	name.push_back("Sableye");
	prop.push_back("Dark Ghost");
	name.push_back("Mawile");
	prop.push_back("Steel Fairy");
	name.push_back("Aron");
	prop.push_back("Steel Rock");
	name.push_back("Lairon");
	prop.push_back("Steel Rock");
	name.push_back("Aggron");
	prop.push_back("Steel Rock");
	name.push_back("Meditite");
	prop.push_back("Fighting Psychic");
	name.push_back("Medicham");
	prop.push_back("Fighting Psychic");
	name.push_back("Electrike");
	prop.push_back("Electric");
	name.push_back("Manectric");
	prop.push_back("Electric");
	name.push_back("Plusle");
	prop.push_back("Electric");
	name.push_back("Minun");
	prop.push_back("Electric");
	name.push_back("Volbeat");
	prop.push_back("Bug");
	name.push_back("Illumise");
	prop.push_back("Bug");
	name.push_back("Roselia");
	prop.push_back("Grass Poison");
	name.push_back("Gulpin");
	prop.push_back("Poison");
	name.push_back("Swalot");
	prop.push_back("Poison");
	name.push_back("Carvanha");
	prop.push_back("Water Dark");
	name.push_back("Sharpedo");
	prop.push_back("Water Dark");
	name.push_back("Wailmer");
	prop.push_back("Water");
	name.push_back("Wailord");
	prop.push_back("Water");
	name.push_back("Numel");
	prop.push_back("Fire Ground");
	name.push_back("Camerupt");
	prop.push_back("Fire Ground");
	name.push_back("Torkoal");
	prop.push_back("Fire");
	name.push_back("Spoink");
	prop.push_back("Psychic");
	name.push_back("Grumpig");
	prop.push_back("Psychic");
	name.push_back("Spinda");
	prop.push_back("Normal");
	name.push_back("Trapinch");
	prop.push_back("Ground");
	name.push_back("Vibrava");
	prop.push_back("Ground Dragon");
	name.push_back("Flygon");
	prop.push_back("Ground Dragon");
	name.push_back("Cacnea");
	prop.push_back("Grass");
	name.push_back("Cacturne");
	prop.push_back("Grass Dark");
	name.push_back("Swablu");
	prop.push_back("Normal Flying");
	name.push_back("Altaria");
	prop.push_back("Dragon Flying");
	name.push_back("Zangoose");
	prop.push_back("Normal");
	name.push_back("Seviper");
	prop.push_back("Poison");
	name.push_back("Lunatone");
	prop.push_back("Rock Psychic");
	name.push_back("Solrock");
	prop.push_back("Rock Psychic");
	name.push_back("Barboach");
	prop.push_back("Water Ground");
	name.push_back("Whiscash");
	prop.push_back("Water Ground");
	name.push_back("Corphish");
	prop.push_back("Water");
	name.push_back("Crawdaunt");
	prop.push_back("Water Dark");
	name.push_back("Baltoy");
	prop.push_back("Ground Psychic");
	name.push_back("Claydol");
	prop.push_back("Ground Psychic");
	name.push_back("Lileep");
	prop.push_back("Rock Grass");
	name.push_back("Cradily");
	prop.push_back("Rock Grass");
	name.push_back("Anorith");
	prop.push_back("Rock Bug");
	name.push_back("Armaldo");
	prop.push_back("Rock Bug");
	name.push_back("Feebas");
	prop.push_back("Water");
	name.push_back("Milotic");
	prop.push_back("Water");
	name.push_back("Castform");
	prop.push_back("Normal");
	name.push_back("Kecleon");
	prop.push_back("Normal");
	name.push_back("Shuppet");
	prop.push_back("Ghost");
	name.push_back("Banette");
	prop.push_back("Ghost");
	name.push_back("Duskull");
	prop.push_back("Ghost");
	name.push_back("Dusclops");
	prop.push_back("Ghost");
	name.push_back("Tropius");
	prop.push_back("Grass Flying");
	name.push_back("Chimecho");
	prop.push_back("Psychic");
	name.push_back("Absol");
	prop.push_back("Dark");
	name.push_back("Wynaut");
	prop.push_back("Psychic");
	name.push_back("Snorunt");
	prop.push_back("Ice");
	name.push_back("Glalie");
	prop.push_back("Ice");
	name.push_back("Spheal");
	prop.push_back("Ice Water");
	name.push_back("Sealeo");
	prop.push_back("Ice Water");
	name.push_back("Walrein");
	prop.push_back("Ice Water");
	name.push_back("Clamperl");
	prop.push_back("Water");
	name.push_back("Huntail");
	prop.push_back("Water");
	name.push_back("Gorebyss");
	prop.push_back("Water");
	name.push_back("Relicanth");
	prop.push_back("Water Rock");
	name.push_back("Luvdisc");
	prop.push_back("Water");
	name.push_back("Bagon");
	prop.push_back("Dragon");
	name.push_back("Shelgon");
	prop.push_back("Dragon");
	name.push_back("Salamence");
	prop.push_back("Dragon Flying");
	name.push_back("Beldum");
	prop.push_back("Steel Psychic");
	name.push_back("Metang");
	prop.push_back("Steel Psychic");
	name.push_back("Metagross");
	prop.push_back("Steel Psychic");
	name.push_back("Regirock");
	prop.push_back("Rock");
	name.push_back("Regice");
	prop.push_back("Ice");
	name.push_back("Registeel");
	prop.push_back("Steel");
	name.push_back("Latias");
	prop.push_back("Dragon Psychic");
	name.push_back("Latios");
	prop.push_back("Dragon Psychic");
	name.push_back("Kyogre");
	prop.push_back("Water");
	name.push_back("Groudon");
	prop.push_back("Ground");
	name.push_back("Rayquaza");
	prop.push_back("Dragon Flying");
	name.push_back("Jirachi");
	prop.push_back("Steel Psychic");
	name.push_back("Deoxys");
	prop.push_back("Psychic");
	name.push_back("Turtwig");
	prop.push_back("Grass");
	name.push_back("Grotle");
	prop.push_back("Grass");
	name.push_back("Torterra");
	prop.push_back("Grass Ground");
	name.push_back("Chimchar");
	prop.push_back("Fire");
	name.push_back("Monferno");
	prop.push_back("Fire Fighting");
	name.push_back("Infernape");
	prop.push_back("Fire Fighting");
	name.push_back("Piplup");
	prop.push_back("Water");
	name.push_back("Prinplup");
	prop.push_back("Water");
	name.push_back("Empoleon");
	prop.push_back("Water Steel");
	name.push_back("Starly");
	prop.push_back("Normal Flying");
	name.push_back("Staravia");
	prop.push_back("Normal Flying");
	name.push_back("Staraptor");
	prop.push_back("Normal Flying");
	name.push_back("Bidoof");
	prop.push_back("Normal");
	name.push_back("Bibarel");
	prop.push_back("Normal Water");
	name.push_back("Kricketot");
	prop.push_back("Bug");
	name.push_back("Kricketune");
	prop.push_back("Bug");
	name.push_back("Shinx");
	prop.push_back("Electric");
	name.push_back("Luxio");
	prop.push_back("Electric");
	name.push_back("Luxray");
	prop.push_back("Electric");
	name.push_back("Budew");
	prop.push_back("Grass Poison");
	name.push_back("Roserade");
	prop.push_back("Grass Poison");
	name.push_back("Cranidos");
	prop.push_back("Rock");
	name.push_back("Rampardos");
	prop.push_back("Rock");
	name.push_back("Shieldon");
	prop.push_back("Rock Steel");
	name.push_back("Bastiodon");
	prop.push_back("Rock Steel");
	name.push_back("Burmy");
	prop.push_back("Bug");
	name.push_back("Wormadam");
	prop.push_back("Bug Grass");
	name.push_back("Mothim");
	prop.push_back("Bug Flying");
	name.push_back("Combee");
	prop.push_back("Bug Flying");
	name.push_back("Vespiquen");
	prop.push_back("Bug Flying");
	name.push_back("Pachirisu");
	prop.push_back("Electric");
	name.push_back("Buizel");
	prop.push_back("Water");
	name.push_back("Floatzel");
	prop.push_back("Water");
	name.push_back("Cherubi");
	prop.push_back("Grass");
	name.push_back("Cherrim");
	prop.push_back("Grass");
	name.push_back("Shellos");
	prop.push_back("Water");
	name.push_back("Gastrodon");
	prop.push_back("Water Ground");
	name.push_back("Ambipom");
	prop.push_back("Normal");
	name.push_back("Drifloon");
	prop.push_back("Ghost Flying");
	name.push_back("Drifblim");
	prop.push_back("Ghost Flying");
	name.push_back("Buneary");
	prop.push_back("Normal");
	name.push_back("Lopunny");
	prop.push_back("Normal");
	name.push_back("Mismagius");
	prop.push_back("Ghost");
	name.push_back("Honchkrow");
	prop.push_back("Dark Flying");
	name.push_back("Glameow");
	prop.push_back("Normal");
	name.push_back("Purugly");
	prop.push_back("Normal");
	name.push_back("Chingling");
	prop.push_back("Psychic");
	name.push_back("Stunky");
	prop.push_back("Poison Dark");
	name.push_back("Skuntank");
	prop.push_back("Poison Dark");
	name.push_back("Bronzor");
	prop.push_back("Steel Psychic");
	name.push_back("Bronzong");
	prop.push_back("Steel Psychic");
	name.push_back("Bonsly");
	prop.push_back("Rock");
	name.push_back("Mime Jr.");
	prop.push_back("Psychic Fairy");
	name.push_back("Happiny");
	prop.push_back("Normal");
	name.push_back("Chatot");
	prop.push_back("Normal Flying");
	name.push_back("Spiritomb");
	prop.push_back("Ghost Dark");
	name.push_back("Gible");
	prop.push_back("Dragon Ground");
	name.push_back("Gabite");
	prop.push_back("Dragon Ground");
	name.push_back("Garchomp");
	prop.push_back("Dragon Ground");
	name.push_back("Munchlax");
	prop.push_back("Normal");
	name.push_back("Riolu");
	prop.push_back("Fighting");
	name.push_back("Lucario");
	prop.push_back("Fighting Steel");
	name.push_back("Hippopotas");
	prop.push_back("Ground");
	name.push_back("Hippowdon");
	prop.push_back("Ground");
	name.push_back("Skorupi");
	prop.push_back("Poison Bug");
	name.push_back("Drapion");
	prop.push_back("Poison Dark");
	name.push_back("Croagunk");
	prop.push_back("Poison Fighting");
	name.push_back("Toxicroak");
	prop.push_back("Poison Fighting");
	name.push_back("Carnivine");
	prop.push_back("Grass");
	name.push_back("Finneon");
	prop.push_back("Water");
	name.push_back("Lumineon");
	prop.push_back("Water");
	name.push_back("Mantyke");
	prop.push_back("Water Flying");
	name.push_back("Snover");
	prop.push_back("Grass Ice");
	name.push_back("Abomasnow");
	prop.push_back("Grass Ice");
	name.push_back("Weavile");
	prop.push_back("Dark Ice");
	name.push_back("Magnezone");
	prop.push_back("Electric Steel");
	name.push_back("Lickilicky");
	prop.push_back("Normal");
	name.push_back("Rhyperior");
	prop.push_back("Ground Rock");
	name.push_back("Tangrowth");
	prop.push_back("Grass");
	name.push_back("Electivire");
	prop.push_back("Electric");
	name.push_back("Magmortar");
	prop.push_back("Fire");
	name.push_back("Togekiss");
	prop.push_back("Fairy Flying");
	name.push_back("Yanmega");
	prop.push_back("Bug Flying");
	name.push_back("Leafeon");
	prop.push_back("Grass");
	name.push_back("Glaceon");
	prop.push_back("Ice");
	name.push_back("Gliscor");
	prop.push_back("Ground Flying");
	name.push_back("Mamoswine");
	prop.push_back("Ice Ground");

	// 474

	name.push_back("Porygon-Z");
	prop.push_back("Normal");
	name.push_back("Gallade");
	prop.push_back("Psychic Fighting");
	name.push_back("Probopass");
	prop.push_back("Rock Steel");
	name.push_back("Dusknoir");
	prop.push_back("Ghost");
	name.push_back("Froslass");
	prop.push_back("Ice Ghost");
	name.push_back("Rotom");
	prop.push_back("Electric Ghost");
	name.push_back("Uxie");
	prop.push_back("Psychic");
	name.push_back("Mesprit");
	prop.push_back("Psychic");
	name.push_back("Azelf");
	prop.push_back("Psychic");
	name.push_back("Dialga");
	prop.push_back("Steel Dragon");
	name.push_back("Palkia");
	prop.push_back("Water Dragon");
	name.push_back("Heatran");
	prop.push_back("Fire Steel");
	name.push_back("Regigigas");
	prop.push_back("Normal");
	name.push_back("Giratina");
	prop.push_back("Ghost Dragon");
	name.push_back("Cresselia");
	prop.push_back("Psychic");
	name.push_back("Phione");
	prop.push_back("Water");
	name.push_back("Manaphy");
	prop.push_back("Water");
	name.push_back("Darkrai");
	prop.push_back("Dark");
	name.push_back("Shaymin");
	prop.push_back("Grass");
	name.push_back("Arceus");
	prop.push_back("Normal");
	name.push_back("Victini");
	prop.push_back("Psychic Fire");
	name.push_back("Snivy");
	prop.push_back("Grass");
	name.push_back("Servine");
	prop.push_back("Grass");
	name.push_back("Serperior");
	prop.push_back("Grass");
	name.push_back("Tepig");
	prop.push_back("Fire");
	name.push_back("Pignite");
	prop.push_back("Fire Fighting");
	name.push_back("Emboar");
	prop.push_back("Fire Fighting");
	name.push_back("Oshawott");
	prop.push_back("Water");
	name.push_back("Dewott");
	prop.push_back("Water");
	name.push_back("Samurott");
	prop.push_back("Water");
	name.push_back("Patrat");
	prop.push_back("Normal");
	name.push_back("Watchog");
	prop.push_back("Normal");
	name.push_back("Lillipup");
	prop.push_back("Normal");
	name.push_back("Herdier");
	prop.push_back("Normal");
	name.push_back("Stoutland");
	prop.push_back("Normal");
	name.push_back("Purrloin");
	prop.push_back("Dark");
	name.push_back("Liepard");
	prop.push_back("Dark");
	name.push_back("Pansage");
	prop.push_back("Grass");
	name.push_back("Simisage");
	prop.push_back("Grass");
	name.push_back("Pansear");
	prop.push_back("Fire");
	name.push_back("Simisear");
	prop.push_back("Fire");
	name.push_back("Panpour");
	prop.push_back("Water");
	name.push_back("Simipour");
	prop.push_back("Water");
	name.push_back("Munna");
	prop.push_back("Psychic");
	name.push_back("Musharna");
	prop.push_back("Psychic");
	name.push_back("Pidove");
	prop.push_back("Normal Flying");
	name.push_back("Tranquill");
	prop.push_back("Normal Flying");
	name.push_back("Unfezant");
	prop.push_back("Normal Flying");
	name.push_back("Blitzle");
	prop.push_back("Electric");
	name.push_back("Zebstrika");
	prop.push_back("Electric");
	name.push_back("Roggenrola");
	prop.push_back("Rock");
	name.push_back("Boldore");
	prop.push_back("Rock");
	name.push_back("Gigalith");
	prop.push_back("Rock");
	name.push_back("Woobat");
	prop.push_back("Psychic Flying");
	name.push_back("Swoobat");
	prop.push_back("Psychic Flying");
	name.push_back("Drilbur");
	prop.push_back("Ground");
	name.push_back("Excadrill");
	prop.push_back("Ground Steel");
	name.push_back("Audino");
	prop.push_back("Normal");
	name.push_back("Timburr");
	prop.push_back("Fighting");
	name.push_back("Gurdurr");
	prop.push_back("Fighting");
	name.push_back("Conkeldurr");
	prop.push_back("Fighting");
	name.push_back("Tympole");
	prop.push_back("Water");
	name.push_back("Palpitoad");
	prop.push_back("Water Ground");
	name.push_back("Seismitoad");
	prop.push_back("Water Ground");
	name.push_back("Throh");
	prop.push_back("Fighting");
	name.push_back("Sawk");
	prop.push_back("Fighting");
	name.push_back("Sewaddle");
	prop.push_back("Bug Grass");
	name.push_back("Swadloon");
	prop.push_back("Bug Grass");
	name.push_back("Leavanny");
	prop.push_back("Bug Grass");
	name.push_back("Venipede");
	prop.push_back("Bug Poison");
	name.push_back("Whirlipede");
	prop.push_back("Bug Poison");
	name.push_back("Scolipede");
	prop.push_back("Bug Poison");
	name.push_back("Cottonee");
	prop.push_back("Grass Fairy");
	name.push_back("Whimsicott");
	prop.push_back("Grass Fairy");
	name.push_back("Petilil");
	prop.push_back("Grass");
	name.push_back("Lilligant");
	prop.push_back("Grass");
	name.push_back("Basculin");
	prop.push_back("Water");
	name.push_back("Sandile");
	prop.push_back("Ground Dark");
	name.push_back("Krokorok");
	prop.push_back("Ground Dark");
	name.push_back("Krookodile");
	prop.push_back("Ground Dark");
	name.push_back("Darumaka");
	prop.push_back("Fire");
	name.push_back("Darmanitan");
	prop.push_back("Fire");
	name.push_back("Maractus");
	prop.push_back("Grass");
	name.push_back("Dwebble");
	prop.push_back("Bug Rock");
	name.push_back("Crustle");
	prop.push_back("Bug Rock");
	name.push_back("Scraggy");
	prop.push_back("Dark Fighting");
	name.push_back("Scrafty");
	prop.push_back("Dark Fighting");
	name.push_back("Sigilyph");
	prop.push_back("Psychic Flying");
	name.push_back("Yamask");
	prop.push_back("Ghost");
	name.push_back("Cofagrigus");
	prop.push_back("Ghost");
	name.push_back("Tirtouga");
	prop.push_back("Water Rock");
	name.push_back("Carracosta");
	prop.push_back("Water Rock");
	name.push_back("Archen");
	prop.push_back("Rock Flying");
	name.push_back("Archeops");
	prop.push_back("Rock Flying");
	name.push_back("Trubbish");
	prop.push_back("Poison");
	name.push_back("Garbodor");
	prop.push_back("Poison");
	name.push_back("Zorua");
	prop.push_back("Dark");
	name.push_back("Zoroark");
	prop.push_back("Dark");
	name.push_back("Minccino");
	prop.push_back("Normal");
	name.push_back("Cinccino");
	prop.push_back("Normal");
	name.push_back("Gothita");
	prop.push_back("Psychic");
	name.push_back("Gothorita");
	prop.push_back("Psychic");
	name.push_back("Gothitelle");
	prop.push_back("Psychic");
	name.push_back("Solosis");
	prop.push_back("Psychic");
	name.push_back("Duosion");
	prop.push_back("Psychic");
	name.push_back("Reuniclus");
	prop.push_back("Psychic");
	name.push_back("Ducklett");
	prop.push_back("Water Flying");
	name.push_back("Swanna");
	prop.push_back("Water Flying");
	name.push_back("Vanillite");
	prop.push_back("Ice");
	name.push_back("Vanillish");
	prop.push_back("Ice");
	name.push_back("Vanilluxe");
	prop.push_back("Ice");
	name.push_back("Deerling");
	prop.push_back("Normal Grass");
	name.push_back("Sawsbuck");
	prop.push_back("Normal Grass");
	name.push_back("Emolga");
	prop.push_back("Electric Flying");
	name.push_back("Karrablast");
	prop.push_back("Bug");
	name.push_back("Escavalier");
	prop.push_back("Bug Steel");
	name.push_back("Foongus");
	prop.push_back("Grass Poison");
	name.push_back("Amoonguss");
	prop.push_back("Grass Poison");
	name.push_back("Frillish");
	prop.push_back("Water Ghost");
	name.push_back("Jellicent");
	prop.push_back("Water Ghost");
	name.push_back("Alomomola");
	prop.push_back("Water");
	name.push_back("Joltik");
	prop.push_back("Bug Electric");
	name.push_back("Galvantula");
	prop.push_back("Bug Electric");
	name.push_back("Ferroseed");
	prop.push_back("Grass Steel");
	name.push_back("Ferrothorn");
	prop.push_back("Grass Steel");
	name.push_back("Klink");
	prop.push_back("Steel");
	name.push_back("Klang");
	prop.push_back("Steel");
	name.push_back("Klinklang");
	prop.push_back("Steel");
	name.push_back("Tynamo");
	prop.push_back("Electric");
	name.push_back("Eelektrik");
	prop.push_back("Electric");
	name.push_back("Eelektross");
	prop.push_back("Electric");
	name.push_back("Elgyem");
	prop.push_back("Psychic");
	name.push_back("Beheeyem");
	prop.push_back("Psychic");
	name.push_back("Litwick");
	prop.push_back("Ghost Fire");
	name.push_back("Lampent");
	prop.push_back("Ghost Fire");
	name.push_back("Chandelure");
	prop.push_back("Ghost Fire");
	name.push_back("Axew");
	prop.push_back("Dragon");
	name.push_back("Fraxure");
	prop.push_back("Dragon");
	name.push_back("Haxorus");
	prop.push_back("Dragon");
	name.push_back("Cubchoo");
	prop.push_back("Ice");
	name.push_back("Beartic");
	prop.push_back("Ice");
	name.push_back("Cryogonal");
	prop.push_back("Ice");
	name.push_back("Shelmet");
	prop.push_back("Bug");
	name.push_back("Accelgor");
	prop.push_back("Bug");
	name.push_back("Stunfisk");
	prop.push_back("Electric Ground");
	name.push_back("Mienfoo");
	prop.push_back("Fighting");
	name.push_back("Mienshao");
	prop.push_back("Fighting");
	name.push_back("Druddigon");
	prop.push_back("Dragon");
	name.push_back("Golett");
	prop.push_back("Ground Ghost");
	name.push_back("Golurk");
	prop.push_back("Ground Ghost");
	name.push_back("Pawniard");
	prop.push_back("Dark Steel");
	name.push_back("Bisharp");
	prop.push_back("Dark Steel");
	name.push_back("Bouffalant");
	prop.push_back("Normal");
	name.push_back("Rufflet");
	prop.push_back("Normal Flying");
	name.push_back("Braviary");
	prop.push_back("Normal Flying");
	name.push_back("Vullaby");
	prop.push_back("Dark Flying");
	name.push_back("Mandibuzz");
	prop.push_back("Dark Flying");
	name.push_back("Heatmor");
	prop.push_back("Fire");
	name.push_back("Durant");
	prop.push_back("Bug Steel");
	name.push_back("Deino");
	prop.push_back("Dark Dragon");
	name.push_back("Zweilous");
	prop.push_back("Dark Dragon");
	name.push_back("Hydreigon");
	prop.push_back("Dark Dragon");
	name.push_back("Larvesta");
	prop.push_back("Bug Fire");
	name.push_back("Volcarona");
	prop.push_back("Bug Fire");
	name.push_back("Cobalion");
	prop.push_back("Steel Fighting");
	name.push_back("Terrakion");
	prop.push_back("Rock Fighting");
	name.push_back("Virizion");
	prop.push_back("Grass Fighting");
	name.push_back("Tornadus");
	prop.push_back("Flying");
	name.push_back("Thundurus");
	prop.push_back("Electric Flying");
	name.push_back("Reshiram");
	prop.push_back("Dragon Fire");
	name.push_back("Zekrom");
	prop.push_back("Dragon Electric");
	name.push_back("Landorus");
	prop.push_back("Ground Flying");
	name.push_back("Kyurem");
	prop.push_back("Dragon Ice");
	name.push_back("Keldeo");
	prop.push_back("Water Fighting");
	name.push_back("Meloetta");
	prop.push_back("Normal Psychic");
	name.push_back("Genesect");
	prop.push_back("Bug Steel");
	name.push_back("Chespin");
	prop.push_back("Grass");
	name.push_back("Quilladin");
	prop.push_back("Grass");
	name.push_back("Chesnaught");
	prop.push_back("Grass Fighting");
	name.push_back("Fennekin");
	prop.push_back("Fire");
	name.push_back("Braixen");
	prop.push_back("Fire");
	name.push_back("Delphox");
	prop.push_back("Fire Psychic");
	name.push_back("Froakie");
	prop.push_back("Water");
	name.push_back("Frogadier");
	prop.push_back("Water");
	name.push_back("Greninja");
	prop.push_back("Water Dark");
	name.push_back("Bunnelby");
	prop.push_back("Normal");
	name.push_back("Diggersby");
	prop.push_back("Normal Ground");
	name.push_back("Fletchling");
	prop.push_back("Normal Flying");
	name.push_back("Fletchinder");
	prop.push_back("Fire Flying");
	name.push_back("Talonflame");
	prop.push_back("Fire Flying");
	name.push_back("Scatterbug");
	prop.push_back("Bug");
	name.push_back("Spewpa");
	prop.push_back("Bug");
	name.push_back("Vivillon");
	prop.push_back("Bug Flying");
	name.push_back("Litleo");
	prop.push_back("Fire Normal");
	name.push_back("Pyroar");
	prop.push_back("Fire Normal");

	// 669
	name.push_back("Flabébé");
	prop.push_back("Fairy");
	name.push_back("Floette");
	prop.push_back("Fairy");
	name.push_back("Florges");
	prop.push_back("Fairy");
	name.push_back("Skiddo");
	prop.push_back("Grass");
	name.push_back("Gogoat");
	prop.push_back("Grass");
	name.push_back("Pancham");
	prop.push_back("Fighting");
	name.push_back("Pangoro");
	prop.push_back("Fighting Dark");
	name.push_back("Furfrou");
	prop.push_back("Normal");
	name.push_back("Espurr");
	prop.push_back("Psychic");
	name.push_back("Meowstic");
	prop.push_back("Psychic");
	name.push_back("Honedge");
	prop.push_back("Steel Ghost");
	name.push_back("Doublade");
	prop.push_back("Steel Ghost");
	name.push_back("Aegislash");
	prop.push_back("Steel Ghost");
	name.push_back("Spritzee");
	prop.push_back("Fairy");
	name.push_back("Aromatisse");
	prop.push_back("Fairy");
	name.push_back("Swirlix");
	prop.push_back("Fairy");
	name.push_back("Slurpuff");
	prop.push_back("Fairy");
	name.push_back("Inkay");
	prop.push_back("Dark Psychic");
	name.push_back("Malamar");
	prop.push_back("Dark Psychic");
	name.push_back("Binacle");
	prop.push_back("Rock Water");
	name.push_back("Barbaracle");
	prop.push_back("Rock Water");
	name.push_back("Skrelp");
	prop.push_back("Poison Water");
	name.push_back("Dragalge");
	prop.push_back("Poison Dragon");
	name.push_back("Clauncher");
	prop.push_back("Water");
	name.push_back("Clawitzer");
	prop.push_back("Water");
	name.push_back("Helioptile");
	prop.push_back("Electric Normal");
	name.push_back("Heliolisk");
	prop.push_back("Electric Normal");
	name.push_back("Tyrunt");
	prop.push_back("Rock Dragon");
	name.push_back("Tyrantrum");
	prop.push_back("Rock Dragon");
	name.push_back("Amaura");
	prop.push_back("Rock Ice");
	name.push_back("Aurorus");
	prop.push_back("Rock Ice");
	name.push_back("Sylveon");
	prop.push_back("Fairy");
	name.push_back("Hawlucha");
	prop.push_back("Fighting Flying");
	name.push_back("Dedenne");
	prop.push_back("Electric Fairy");
	name.push_back("Carbink");
	prop.push_back("Rock Fairy");
	name.push_back("Goomy");
	prop.push_back("Dragon");
	name.push_back("Sliggoo");
	prop.push_back("Dragon");
	name.push_back("Goodra");
	prop.push_back("Dragon");
	name.push_back("Klefki");
	prop.push_back("Steel Fairy");
	name.push_back("Phantump");
	prop.push_back("Ghost Grass");
	name.push_back("Trevenant");
	prop.push_back("Ghost Grass");
	name.push_back("Pumpkaboo");
	prop.push_back("Ghost Grass");
	name.push_back("Gourgeist");
	prop.push_back("Ghost Grass");
	name.push_back("Bergmite");
	prop.push_back("Ice");
	name.push_back("Avalugg");
	prop.push_back("Ice");
	name.push_back("Noibat");
	prop.push_back("Flying Dragon");
	name.push_back("Noivern");
	prop.push_back("Flying Dragon");
	name.push_back("Xerneas");
	prop.push_back("Fairy");
	name.push_back("Yveltal");
	prop.push_back("Dark Flying");
	name.push_back("Zygarde");
	prop.push_back("Dragon Ground");


	int n;
	scanf("%d", &n);

	printf("%s\n%s\n", name[n].c_str(), prop[n].c_str());

}